// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DataItem is an autogenerated mock type for the DataItem type
type DataItem struct {
	mock.Mock
}

type DataItem_Expecter struct {
	mock *mock.Mock
}

func (_m *DataItem) EXPECT() *DataItem_Expecter {
	return &DataItem_Expecter{mock: &_m.Mock}
}

// NewDataItem creates a new instance of DataItem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataItem(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataItem {
	mock := &DataItem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
